//! End-to-end: a real exported 105-plane / 4288-policy / tanh-scalar net
//! loads in ORT, evaluates white- and black-to-move positions with finite
//! per-legal logits and a sane STM-frame cp in [-400, 400].
//!
//! Run: cargo test --release -p nn --test onnx_4288
//! Needs the ORT DLL (Python onnxruntime install) + a GPU (falls back
//! to CPU). Training must be stopped (GPU memory).
//!
//! The net asset (tests/data/net105_4288.onnx) is generated by
//! python/make_test_net.py from the repo's own exporter.

use engine::movegen::generate_legal;
use engine::position::Position;

const NET: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/data/net105_4288.onnx"
);

#[test]
fn onnx_4288_loads_and_evaluates_both_colors() {
    engine::init();
    nn::onnx::OnnxEvaluator::init(NET, 8).expect("4288 net must load");

    // White to move: startpos.
    let white = Position::startpos();
    let legal_w = generate_legal(&white);
    // Black to move: after 1.e4.
    let mut black = Position::startpos();
    {
        let mv = legal_w
            .iter()
            .find(|m| m.to_uci() == "e2e4")
            .expect("e2e4 legal");
        black.make_move(mv);
    }
    let legal_b = generate_legal(&black);
    assert!(black.side == 1);

    let out = nn::onnx::batch_evaluate_onnx(&[white, black], &[&legal_w, &legal_b]);
    assert_eq!(out.len(), 2);
    for ((cp, logits), legal) in out.iter().zip([&legal_w, &legal_b]) {
        assert_eq!(logits.len(), legal.len, "one logit per legal move");
        assert!(
            cp.abs() <= 400,
            "tanh scalar maps to STM cp in [-400, 400], got {cp}"
        );
        assert!(
            logits.iter().all(|x| x.is_finite()),
            "all policy logits finite"
        );
    }
    // Same batch twice must be bit-identical (stateless inference).
    // Across batch SHAPES, kernels may differ (TF32 heuristics): allow
    // small drift, flag large drift.
    let out2 = nn::onnx::batch_evaluate_onnx(&[white, black], &[&legal_w, &legal_b]);
    for (a, b) in out.iter().zip(out2.iter()) {
        assert_eq!(a.1, b.1, "same batch must be bit-identical");
    }
    let out3 = nn::onnx::batch_evaluate_onnx(&[white], &[&legal_w]);
    let maxdiff = out[0]
        .1
        .iter()
        .zip(out3[0].1.iter())
        .map(|(a, b)| (a - b).abs())
        .fold(0.0f32, f32::max);
    assert!(
        maxdiff < 5e-3,
        "cross-batch numeric drift too large: {maxdiff}"
    );
}
